server:
  port: 6099
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: redis-demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    password: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true